name: renty
description: College item rental app
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

# Flutter assets configuration
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.4.0
  riverpod_annotation: ^2.3.0
  
  # UI/UX
  material_color_utilities: 0.11.1
  google_fonts: ^5.1.0
  flutter_animate: ^4.2.0
  shimmer: ^3.0.0
  cached_network_image: ^3.3.0
  image_picker: ^1.0.4
  
  # Firebase
  firebase_core: ^2.15.1
  firebase_auth: ^4.9.0
  cloud_firestore: ^4.9.1
  firebase_storage: ^11.2.6
  firebase_messaging: ^14.6.7
  
  # Auth
  google_sign_in: ^6.1.0
  
  # Payments
  # razorpay_flutter: ^1.3.5  # Temporarily commented out due to fluttertoast namespace issue
  
  # Navigation
  go_router: ^10.0.0
  
  # Network
  dio: ^5.3.2
  connectivity_plus: ^4.0.2
  
  # Utils
  intl: ^0.18.1
  uuid: ^3.0.7
  # permission_handler: 10.2.0  # Temporarily commented out due to v1 embedding issue
  shared_preferences: ^2.2.0
  
  # Image handling
  image: ^4.1.3
  equatable: ^2.0.7
  animate_do: ^4.2.0
  dartz: ^0.10.1
  timeago: ^3.7.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  riverpod_generator: ^2.3.0
  build_runner: ^2.4.7
  mockito: ^5.4.2
  integration_test:
    sdk: flutter
