name: renty
description: College item rental app
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.4.0
  riverpod_annotation: ^2.3.0
  
  # UI/UX
  material_color_utilities: 0.11.1
  google_fonts: ^6.1.0
  flutter_animate: ^4.2.0
  shimmer: ^3.0.0
  cached_network_image: ^3.3.0
  image_picker: ^1.0.4
  
  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  firebase_messaging: ^14.7.10
  
  # Auth
  google_sign_in: ^6.1.5
  
  # Payments
  razorpay_flutter: ^1.3.6
  
  # Navigation
  go_router: ^12.1.3
  
  # Network
  dio: ^5.3.4
  connectivity_plus: ^5.0.2
  
  # Utils
  intl: ^0.19.0
  uuid: ^4.2.1
  permission_handler: ^11.1.0
  shared_preferences: ^2.2.2
  
  # Image handling
  image: ^4.1.3
  equatable: ^2.0.7
  animate_do: ^4.2.0
  dartz: ^0.10.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  riverpod_generator: ^2.3.0
  build_runner: ^2.4.7
  mockito: ^5.4.2
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
