// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdq_yYAHeL3_NeK0YrKYSWIVWZNoiqw70',
    appId: '1:704691504148:web:f9d6f8506dd718dcedd301',
    messagingSenderId: '704691504148',
    projectId: 'renty-65844',
    authDomain: 'renty-65844.firebaseapp.com',
    storageBucket: 'renty-65844.firebasestorage.app',
    measurementId: 'G-77F0Y15LDS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBun_SbL_zrDHdQHmi0U_TZ-JVYvn9RQ7g',
    appId: '1:704691504148:android:63a7fc8252e8b30fedd301',
    messagingSenderId: '704691504148',
    projectId: 'renty-65844',
    storageBucket: 'renty-65844.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKZTnm9uW-BfA31nWzaJitj11c8UBWh40',
    appId: '1:704691504148:ios:e2b87e1dfd9b5aa7edd301',
    messagingSenderId: '704691504148',
    projectId: 'renty-65844',
    storageBucket: 'renty-65844.firebasestorage.app',
    iosBundleId: 'com.example.ciaRenty',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKZTnm9uW-BfA31nWzaJitj11c8UBWh40',
    appId: '1:704691504148:ios:e2b87e1dfd9b5aa7edd301',
    messagingSenderId: '704691504148',
    projectId: 'renty-65844',
    storageBucket: 'renty-65844.firebasestorage.app',
    iosBundleId: 'com.example.ciaRenty',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdq_yYAHeL3_NeK0YrKYSWIVWZNoiqw70',
    appId: '1:704691504148:web:ebec83f4b1ee7f23edd301',
    messagingSenderId: '704691504148',
    projectId: 'renty-65844',
    authDomain: 'renty-65844.firebaseapp.com',
    storageBucket: 'renty-65844.firebasestorage.app',
    measurementId: 'G-5XXVE54NTJ',
  );

}